### ISSUE TITLE
Unit First Strike

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#112]
A feature that would, in my opinion, greatly enhance modding possibilities is a way to specificy that a unit attacks first even when defending, much like Sonja's SCOP.

Here is how I think it should interact with other 'attack first' abilities. Top of the list fires first, bottom fires last.
- Sonja SCOP First Strike Defending
- Sonja SCOP First Strike Attacking
- First Strike Defending
- First Strike Attacking
- Attacker
- Defender

**Comment by Robosturm** [comment]
This is more a new mechanic which can be stated as attack speed, which isn't part of the game.
And i currently don't plan on adding it,
Though you could mod it in by moding the ACTION_FIRE script.

Sonja's First-Strike works different in Advance Wars since the attacker damage remains unchanged.
Only her troops attack as if they didn't recieve damage.

**Comment by Robosturm** [comment]
Remains possible via modding but currently i think i won't add it at all.
Unless you want to to the hacking work
