### ISSUE TITLE
more CO ability toggles in match settings

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1163]
currently there is the toggles for the CO's powers together and the D2D, i think it would be nice to have some more flexibility with the options able to toggle everything individually. 

Day to day - Zone bonus - Swap bonus - CO Power - Super Power - and Tag Power (though no vanilla COs utilize it, the Tag can have its own unique powers beyond the Synergy bonus)

 not as necessary but it would also be a neat feature if it was possible to have the option to code a CO's various abilities to change depending on which abilities are toggled off in the match settings

**Comment by Robosturm** [comment]
Disabling co-power, super power or tag power individually is already possible by banning an action in the rules.

Changing D2D-Effects e.g. only using the abilities of co 1 or 2 or changing global and zone efects isn't possible due to the way rules and the implementation of co's interact. 
Since changing the rule only happens if the co is coded that way, which makes the rules way to buggy/compatible with mods.

As for the 3 request it's already possible to mod in own rules and have them effect co's, if someone is willing to mod that in
