### ISSUE TITLE
2022-12-03 - Issue Log

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1196]
**Preamble**
Due to the number of errors found, I decided to include them in a collection. If this is not a good bug reporting option, please let me know.

**Describe the bug**

**1. Issue - Monitordetection:**
Options -> Video -> Videomode

Screen cannot be preferred with 2 monitors. Alternatively, it would only be possible to adjust the screen to window mode and move it to the respective monitor. It would be good to be able to select this in the program.

**2. Issue - key mapping:**
Although the control left, up, right, left is also assigned to the corresponding direction keys by default, the input is still accepted inversely by the program.

Examples:
Map Editor -> Try using Directional Keys, its also possible to use WASD which are not inverted
Singleplayer -> New Game during that menu the buildings shown below for each map uses the same inverted key configuration
Within Skirmishmaps -> Try using Directional Keys, its also possible to use WASD which are not inverted

**3. Issue - Tiles in Map Editor:**
There are pipeline welds which can be fixed. However, these have an incorrect terrain image which is shown on the bottom right. But there are also pipeline welds which are placed according to the alignment of the pipeline. So I assume that it is an old stock which is no longer needed.
![Map_Editor_Welds](https://user-images.githubusercontent.com/119428442/205438673-120a96a7-dd9a-4c7b-b64a-e4d94861794c.png)

**4. Issue - Movemoent Infantry on Oil Rigs:**
Infantry cannot be set up on oil rigs unless set up on underground land. Was this on purpose?
![Oil_Rig_Infantry](https://user-images.githubusercontent.com/119428442/205438676-141b1b64-4772-47f8-a824-84065bf733c7.png)

**5. Issue - Missile Sub Animation:**
The missile submarine has no movement animation.
![Missile_Sub_withoutmovementAnimation](https://user-images.githubusercontent.com/119428442/205438681-edc56fc1-756e-44eb-9038-90b9ea175c95.png)

**6. Issue - Misslelaunching:**

According to the wiki, missiles can be launched 13 squares away. As an attachment you can see that the rocket can be removed much further (more precisely written it's inf.).
![13_tile_rocket](https://user-images.githubusercontent.com/119428442/205438686-4586400d-5b87-4514-9a7e-b7e331e4cbb9.png)

**7. Issue - Metall Army / Metal Army:**
Which of them is the one which should be used?
![Wiki_Missing_Armyentries](https://user-images.githubusercontent.com/119428442/205438696-efe42e1b-b071-4ea5-a020-16e5df76c4f5.png)

Examples:
all in -> scripts/cos/co_empty_ma.js
- A Blank CO for Metal Army.
- The Metall Army is an army of robots. ...
- The Metall Army defends it's own ...
- Besides this the Metall Army is very ...
- Metal Army

**8. Issue - Blurred_Forest:**
Should be better to use the same picture which is alread implemented for an other forest.
![blurred_version_forest](https://user-images.githubusercontent.com/119428442/205438719-a99b11bd-2d52-4576-8f04-758da8611ca0.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.26.1-main
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
@UOcelot16 Please report every finding in one issue. Since i'll solve or deny issues based on the content. Else the project trackin/management s impossible.
1. Intentional behaviour and support for selecting the screen is very very unlikely to be added
4. That's correct since the building is placed on a sea tile
5. Correct behaviour no sprites exist for that and no plans to change that exist atm
6. It mentions the target area not the range. Behaviour is correct.
7. metal is correct. The missing entries are correct no faction descriptions exists atm and will be missing till the campain is finished
8. Correct behaviour and no intention to be changed. Forest select a random foreground. Those are the original sprites according to K'Braid

**Comment by UOcelot16** [comment]
@Robotsturm: 1 -> 1; 2 -> 4; 3 -> 5?; 4 -> 6; 5 -> 7; 6 -> 8; Please use the already given numbers for each Issue what has been mentioned. This helps for much better unterstanding at what has been answers to. This also includes other dialogues which has been done out of github.

Since you have already partly commented on this entry, which one of them should be rereportet?
2. Issue - key mapping, 3. Issue - Tiles in Map Editor?

8. Issue - Blurred_Forest:
So should I message then K'Braid about the blurried forest Version?

**Comment by Robosturm** [comment]
I actually numerated them correctly but githubs auto numbering messed it up on my smartphone. :(
1 -> create a new issue
2 -> already changed not really a bug since it's moving map not cursor but i understand what you mean -> no issue
3 -> Those pipes are player pipes so they are owned by the player placed and can't be attacked by that player mainly an ai feature -> no issue
4 -> no issue 
5 -> no animation right now nothing that will be changed mostlikely unless K'Braid or Wadaling decide to do something about it. But that's up to them -> so no issue
6 -> no issue behaviour correct
7 -> no issue needed but is part of later releases
8 -> K'Braid told me this is currently the best we can get for forest and he said he won't invest more time for them atm.
