### ISSUE TITLE
Game crash somehow related to getAiCoUnitBonus

### ISSUE THREAD

**Issue by Brilliand** [Robosturm/Commander_Wars#1253]
**Describe the bug**
One of my custom COs is causing the game to crash with an access violation.

**To Reproduce**
I've narrowed this crash down to happening at the start of the turn of a specific custom CO that I made.  Originally, the AI would just never load this CO into a CO unit, and the console would fill up with complaints about a missing getAiCoUnitBonus function.  Once I added that function in, the game began to sometimes crash at the start of this CO's turn.  I'm not sure what triggers it to start crashing, but once it does, it consistently crashes at the same point in the game whenever I load an autosave from before it crashed.

**Expected behavior**
If there's something wrong with the custom CO, that should produce a console warning, not an access violation.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.26.1-main
 - Active Mods: The attached "Contessa" CO, and a few other custom COs

**Additional context**
The (mostly useless) crash log:
[20221214-023238 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/10226348/20221214-023238.Commander.Wars.Crash.log)

The custom CO mod that's crashing the game:
[contessa_co.zip](https://github.com/Robosturm/Commander_Wars/files/10226381/contessa_co.zip)

**Comment by Robosturm** [comment]
Yoou're expectation will never be matched.
The game isn't checking every single input to a c++ function you give it. 
Mainly for improved performance.
If the game crashes due to a modded co you can ask for help in the discord channel but not here.
Unless you can point out a function isn't doing what it should.

Also your crashlog and cozip don't match since the crash log mentions a none existing line.
You may want to enable debug level for tracing the issue.
My initial guess is that ai tries to use the cop which crashes the game you don't have any power sentences defined.
