### ISSUE TITLE
Proposal: Map Editor -> Select Unit Submenu

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1283]
![Screenshot (698)](https://user-images.githubusercontent.com/119428442/209986343-08577f2b-935b-42e8-baa6-863a44cb8a26.png)

**Comment by Robosturm** [comment]
Note changing the text to an icon is impossible since it's a field meant to give the unit a unique name and not for changing the unit type.
Y-Spacing in the menu is the same as in all menus and won't be changed.
Bars and textfields will always use the full x-space they have for easier coding and to be useable on smaller screens
