### ISSUE TITLE
Issue_TL: Double Entry (?)

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1296]
![double entry](https://user-images.githubusercontent.com/119428442/210134633-af5df034-30ee-40fa-9a7c-e5ed4b025a1e.png)
![double_entry_questionmark](https://user-images.githubusercontent.com/119428442/210134634-0f0914c5-daaf-4251-80eb-7f7a69f9cb68.png)

**Comment by Robosturm** [comment]
That's fully correct and intentional.
The first entry is for showing in the game menu when you select it and the second one for the wiki and bann-lists etc.
The Game: surrender game one is an internal solution for seperating the confirmation box from the actual execution.
And is meant not to be selectable in the game menu and has the name Unknown for that reason, so a bug where the action gets visible in the menu is easier to catch.
