### ISSUE TITLE
Strange memory issues when loading custom maps and scripts

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#130]
Some strange corruptions can happen to a saved custom map when transitioning the map from per-deployed to an empty map, where at the start of the match it'll defeat the play missing all of his pre-deployed units. Loading up a map in the editor that had pre-deployed co units will instead just have those units veteraned. Load up a script to edit it will have Player "-" Defeated fields reset to 1. A default Fog of War map played with Fog of War off will have the very first screen be Fogged. Just to name a few thing encountered.

**Comment by Robosturm** [comment]
Could you give me a step by step explanation of what you do and what is the result. Cause I don't understand what exactly is going wrong and what you did to do so.
Something like:
1 did that
2 did that
3 crash happened

**Comment by Everglass** [comment]
For instance, on my graver hill map, there is a sole infantry until located on blue moon's hq. If I where to delete this unit, say to make it compatible with fairy's overhaul, trying to load up a match on this map will instantly go to the post game screen. As if the blue moon lost due to losing all their units.

As for the scripts, it seems for what ever reason that when you load these scripts up to do more editing, some of these fields will reset.
![Scriptbugs](https://user-images.githubusercontent.com/58909501/72677060-7652f200-3a55-11ea-9ef6-bda3e01212c7.png)
This is most just with the Defeat Player Event where it'll be reset to defeat the first player. Also height for for the width and height values for marking area's for trigger conditions will also be reset to zero on load. These issue don't cause any problems when loading the map with the the script however.

Also rules don't get saved, such as setting the starting weather and turning off native win conditions.

**Comment by Robosturm** [comment]
Thx for the reports but please report each bug as a seperate issue to make it easier to understand and easier to track everything. You reported three different bugs here.

A) with your script if the map and the script are not identical the bug is on your side. You have to make sure that a unit is at the given position at the start of the game else the outcome is undefined. The generated javascripts don't check for errors. My guess is that the game immediatly executes the events and your events include defeating a player. Ofc you can modify the sripts by hand. So they check for errors. You can press F1 and see the error log of the gamescript which should say that the access to soemthing was nil.

B) that a sole visual bug since the ingame script data is only loaded/read by a handwritten code for the viewer.

C) Also a sole visual bug if you would start the game by checking the immediat start check box everything would work.

Fixed b and c. A won't get fixed since it's not a bug on my side.

**Comment by Everglass** [comment]
There are no scripts for my Graver Hill map though, just that one deployed unit. If I destroy the unit, and open a game on the map without the No Unit win condition turned off, the game immediately concludes.
