### ISSUE TITLE
More moddablity options for AI descisions

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#136]
It would be neat to have score modifiers in unit and building scripts, to modify the likelihood of the AI to construct certain units, or discourage the AI from attack certain buildings, such attacking towns when made destructible.

**Comment by Robosturm** [comment]
You can manual add some script code to the map scripts to modify what the AI builds same goes for CO's. I may add a callback to mods as well. So it applies game wide.

As for attacking priority of buildings nothing will happen here. Already told something similar Fairy.
Anything exceeding the tasks the AI needs to do in a normal Advance Wars Game is out of scope.

In general anything concerning modding the AI will be rejected in 99% of all cases due to the complexity. Programming the AI for the normal game is already really complex and error thrown. If i would need to account for mods as well. It's just getting impossible.

**Comment by Everglass** [comment]
I see. This is unfortunate but understandable. Thank you for your time.
