### ISSUE TITLE
Issue: v0.28.1-main PreBuild Intro

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1363]
![Screenshot (873)](https://user-images.githubusercontent.com/119428442/211209004-8f58ae8e-ba80-43a2-b24b-81d0fa45718b.png)
![Screenshot (874)](https://user-images.githubusercontent.com/119428442/211209006-560f7c3a-db6f-4472-9109-a33e48068b94.png)

**Comment by UOcelot16** [comment]
?

**Comment by Robosturm** [comment]
It's marked pre-release, which means unfinished.

**Comment by Robosturm** [comment]
If try to use anything marked pre-release expect nothing other than random behaviour

**Comment by UOcelot16** [comment]
That's why I'm sharing what I found. You could also refer to earlier versions of what you write, so what's wrong with it now? What ever...

**Comment by Robosturm** [comment]
As long as a release is marked pre-release it's in crafting state so anything you report in that state doesn't really help.
Cause you try to report something for something that's unfinished and as long as it's unfinished, it doesn't work.
As long as i didn't make a post on discord/marked the release properly, it's not a release.
But i can't hide it from anyone due to the way github works.
So marking it pre-release is the best i can do.

**Comment by UOcelot16** [comment]
Well, then I will focus my attention exclusively only on the releases. But it also means that things found in advance can no longer be communicated.

**Comment by Robosturm** [comment]
Pre-Releases only exists for me trying out some outmated deployment and get deleted afterwards again.
So they are not meant to get feedback and they will never be made/exist to get feedback.
