### ISSUE TITLE
Issue: Oozium Movement v0.1 a.k.a. fast surrender of Enemy Unit

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1369]
Units explode before Oozium has a chance to fully move. Including a little more time for movement should fix this.

**Comment by UOcelot16** [comment]
If this won't be fixed how it is possible to change this as a mod?

**Comment by Robosturm** [comment]
No it will result in buggy behaviour mostlikely

**Comment by UOcelot16** [comment]
Okay. Then how about manually setting more frames into a separated destroyed animation which is for oozium which is also setted with later included sound? So if a unit gets destroyed it get this animation instead so the behaviour shouldn't be displayed.

**Comment by Robosturm** [comment]
No that's not really possible either. The oozium is a weird unit and outside of teleport tiles which are not a common thing as well.
I don't see a visual problem, when the oozium only moves one space.
So the oozium is pretty much a niche unit, which is why i don't want to invest any time into an improvement
