### ISSUE TITLE
Proposal: Map Editor -> Edit Terrain Optical Changes

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1390]
-> Header for Menu (centered), since building and unit have it
-> Linespace between Header and Subheader
-> Much more Linespace between Subheader and Terrain Icon

![grafik](https://user-images.githubusercontent.com/119428442/211622673-55bee3aa-d459-4139-b333-107c1dc10e5f.png)

**Comment by UOcelot16** [comment]
Also testet it for other terraintiles like forest there is also an additional with the same proposal what I would like to mention. It is gernerally better to habe more linespace between header and description or what so ever followed after that. Of course I can make everytime make a proposal for that but how about thinking about that before that?

**Comment by Robosturm** [comment]
The issues with the spacing come from changing the font used by the game and changes in the rendering process of fonts with one of the latest releases. So it's not surprising several of them got broken in one way or the other

**Comment by UOcelot16** [comment]
So it will be something that can only be located if the game has been converted as a playable exe (or what the other OS use)?

**Comment by Robosturm** [comment]
A lot of the ui's are very old and don't use the new xml-generation process but instead have fixed y-advance steps which don't take the actual size of the font into account and since this is an issue for a lot of the ui's you'll stumble about them.
The correct way would be to convert them all into xml-files which automatically generate correct spacing but that's tedious and boring. So i don't really attack that task.
Simple as that

**Comment by UOcelot16** [comment]
This is a very understandable answer. Thanks.
