### ISSUE TITLE
Unnecessary submenus with APCs transporting infantry

### ISSUE THREAD

**Issue by GuardianTempest** [Robosturm/Commander_Wars#14]
**Describe the bug**
When dropping infantry from APCs, you have a submenu for the passenger which only consists of "Wait". An extra button press might not seem like much but it's a bit jarring compared to other units only having the Wait/Atk/Capture command waiting post-movement. On that note, perhaps put the passenger commands into the main post-movement menu instead of under the "Drop" submenu like in the games (especially if there's only one passenger). ~~If a unit is somehow transporting a dozen or so passengers, just break the excess off into a new column instead of a submenu~~

**Additional context**
I'm not sure if the same applies to Landers and other transport units. Also, if this is meant to be intentional (for a CO who allows moving units after being transported), I think the fix should still be applied. When the unit is dropped off it just remains being ready for action, allowing players to shuffle their forces before moving the disembarked unit for greater tactical finesse.

**Comment by Robosturm** [comment]
As for the loading\unloading part. Moving the Units to the top level menu is sadly impossible due to the generic solution which allows you to mod in pretty much anything you want.

What i can think of which is pretty easy addable would be the following:
Dropping the Wait Command when unloading units, when all units are unloaded.
Dropping the select a unit command when only one unit is loaded (not sure if i can easily get out when only one unit can be unloaded -> e.g infantry and tank loaded and only on a mountain can be unloaded) and if it's kinda clever....

**Context of Loading\Unloading Units how it works:**
As for the units beeing moveable that's an intentional behaviour. 
The behaviour is when loading a unit and unloading it at the same turn the unit can't move.
If the unit is unloaded at any turn afterwards it is able to move. I know that's different from the original game though i personally like the idea -> The behaviour could be disabled by a mod. ;)

**Comment by Robosturm** [comment]
Done and thx for the optimization idea. Feels a lot smoother now...

**Comment by GuardianTempest** [comment]
o7

Thank you for addressing the concerns.
