### ISSUE TITLE
Units behind HQs or tall terrains like mountains are hidden and thus their HPs cannot be seen

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#16]
**Describe the bug**
Units standing behind tall terrains like mountains or HQs are hidden by said terrain, and thus their HPs cannot be seen, which hinders gameplay.

**To Reproduce**
1. Go to a map featuring a HQ.
2. Manage to have one of your units damaged (below 10 HPs so that HPs are displayed).
3. Place your damaged unit behind your HQ. Also works with enemy units of course.

**Expected behavior**
HP should be seen through the terrain.

**Screenshots**
I'd like to post a screenshot, I made one and tried to paste it in Gimp but unfortunately it just pasted a white rectangle, not sure why. Couldn't use the snipping tool either because I was playing in fullscreen. Sorry!

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 4

**Comment by Robosturm** [comment]
I know you're feelings.
When i started i was like what's better units beeing always visible or realistic beeing hidden by mountains or HQ.

I checked how Advance Wars 2 is handling it and Advance Wars DoR.
And since some HQ's like the Blue Moon or Orange Star hide 80% of a Unit and since only making the icons be on top of buildings isn't possible with the priority and attachment of the icons.
I decided to make the UI more obvious instead of realistic.
So units are always on top of all the terrain stuff.

Looks like this now -> it's exactly like in AW2
![dummy](https://user-images.githubusercontent.com/48879701/62367943-638e4480-b52b-11e9-9ba9-1e66b9861392.png)
