### ISSUE TITLE
Dialog problems

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#165]
I decided to input 3 bugs in this one issue, because they're pointed to one subject (dialog)

1. For some unknown reason it's impossible to delete last dialog line (clicking on button do nothing, and instead user is forced to delete whole dialog and make it again)

2. After writing 5 dialog lines, creating 6th ends with weird position of scroll. It's impossible to pick CO1 option, only CO2 is available as the first (my resolution is windowed 1280x720 if that's the case)

3. Sometimes (without reason) creating a new dialog line can delete all created earlier dialog lines.

**Comment by Robosturm** [comment]
Okay:
As for 1. The line is actually deleted but it's not getting visually updated.
Point 2 is a result of pressing the delete button multiple times and then pressing the add button. Since the add button acutally updates the gui.
So you deleted the dialog items and press add afterwards and than the gui updates with the removed lines.

As for 3 i have on my list to update the behaviour of drop down menus hopefully for the next release was actually planned for the last release. Since it's currently bad implemented and hardcoded.

**Comment by Danmark25** [comment]
About point 2 (with 6 dialog lines in weird position)

Yesterday during making maps, I had seen that 6 dialog line is always in same position (no matter if earlier line was deleted or not)

Next (7th and later) are working as normal.. that means the scroll box must be too big comparing to window size, or something like that
