### ISSUE TITLE
Game crashing when battle animations are loaded (v33.1)

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1712]
**Describe the bug**
When the animations are loaded, the game seems to crash at semi random times, with the following output on the console:
`Assertion 's' failed at ../src/pulse/stream.c:1705, function pa_stream_writable_size(). Aborting.`

I checked to make sure it wasn't a mod issue, I disabled any mods in the game. This version is also directly the binary generated by the Github actions. 

**To Reproduce**
1. Create a new match between two COs
3. Make 2 units engage in combat while the battle animations are enabled
4. The battle animations will load, but randomly crash the game with the output above
5. See error

**Expected behavior**
The game should not crash if the animations are being loaded

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Version 23.10
 - Active Mods: No active mods
 - Game Version v33.1

**Additional context**

**Comment by Robosturm** [comment]
This is a crash in the pulse linux audio lib. Produced either by qt with linux or by your custom compilation.
Sadly the code works on windows. So I can't reproduce it. Muting sounds should solve the crash

**Comment by lonewolf19991** [comment]
It's the github generated binary. Where should I look into the source code, to try and fix this, assuming it's an interaction between the source code and pulse audio? My guess is audiomanager.cpp or is there another file handling that part of the game?

**Comment by Robosturm** [comment]
The file would be this https://github.com/Robosturm/Commander_Wars/blob/master/coreengine/sounds/ondemandsound.cpp
The issue is mostlikely in the stop function.
My guess is that either qt or the pulse lib don't register the stop destroy calls correctly and still put data on the output qudio stream which got killed already which leads to the crash. And since it depends on if the backend code puts  data on the output or not it randomly crashes.
The issue is that I'm terminatibg things correctly

**Comment by lonewolf19991** [comment]
The v34 compilation here: https://github.com/Robosturm/Commander_Wars/releases/tag/Beta_34_0_Build1 Doesn't crash when the sounds are played anymore, however the thread that handles the audio probably still does, so audio can stop playing at times. I have this suspicion might have to do with memory addresses' handling.
