### ISSUE TITLE
Map Editor Magnet Tool Suggestion

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1719]
**Is your feature request related to a problem? Please describe.**
Manually editing the terrain style so streets/roads connect to adjacent buildings is very time consuming, even when I copy and paste. Additionally, numerous maps in CoW lack the proper street/road styles needed to match with their AW or AWBW versions, and that would take an incredibly long time to fix without this tool.

**Describe the solution you'd like**
Add a "Magnet" tool to the Map editor, which would go into the tool area. When using the magnet tool on a street/road tile, it will change the tile's style to one that will make it connect to adjacent buildings, bridges, and roads.

**Additional context**
Perhaps it could use code similar to the code that makes streets/roads/bridges automatically connect to each other.

Before:
This would take 28 clicks to make the roads lead where desired. 2 to select the tool, and 24 to change all the areas.
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/c22a3bda-6d23-4d67-ad3c-b8947da79097)

After:
This would take 15 clicks to make the roads lead where desired. 1 to select the tool, and 14 to fix the areas. It is also faster because you only need to click the tile, and not open a menu and manually select the one you want.
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/4af5827d-154a-4066-afa8-daf4b76ae50f)

This second feature isn't too important to me, but it would be neat if the magnet tool made tile styles ignore the map edge. Maybe the map editor would be changed so tiles don't connect to edges by default?

Before:
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/e1574086-563e-408d-af13-9e095abbcca6)

After:
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/d5c9d486-96e1-4c0d-9d09-1d3192567c42)

**Comment by Robosturm** [comment]
The intended way to do that (currently bugged) is that you place the road and put a building on top of the road.
The game should treat that tile as a road tile and connect it to the rest of the road.
Of course for some buildings you'll see the road sprite below that,

The magnet idea doesn't fit my idea on how the sandbox engine of CoW is designed.
As for map corners there are and always will be the discussion if the map border should be treated as same tile or not.
In fact similar to wether roads connect to buildings or not both are moddable since the tile selection happens in the js code and is one of the reasons why I don't want to introduce a magnet tool and instead the fixed tile section feature exists which of course is a bit more tedious compared to the magnet tool

**Comment by Robosturm** [comment]
The main issue is that you have two modes for connecting tiles and I only want the engine deal with one and the rest falls under map designing working task
Especially for road like tiles and both have a point and I could never decide which one is better so I stuck to the cartridge version

**Comment by FruityGumGuiltyFruit** [comment]
Alright, thank you.
