### ISSUE TITLE
AI improvement

### ISSUE THREAD

**Issue by Jocrr** [Robosturm/Commander_Wars#1731]
Here's what I said on Discord
![image](https://github.com/Robosturm/Commander_Wars/assets/93048095/c9fd59b8-25d3-48a2-b6fe-41c16aef5cb3)
![image](https://github.com/Robosturm/Commander_Wars/assets/93048095/9add1a90-8237-4fc9-a15e-190f0c25c8f9)

**Comment by Jocrr** [comment]
Couldn't this be left open and labelled as help wanted or something so maybe someone else could fix the Ai then?

**Comment by Robosturm** [comment]
No. Since this project started no one ever wanted to make code contributions.
And if so starting with AI stuff isn't recommend and I'm certainly not wasting my time on something like that.
If there are AI bugs they will be fixed but I'm not trying to emulate any orginal AW stuff and playing on an island map and expecting something else than a slug against an ai is naive and pointless.

**Comment by Jocrr** [comment]
☹️
