### ISSUE TITLE
please add option to enlarge image

### ISSUE THREAD

**Issue by He-maxed** [Robosturm/Commander_Wars#1798]
please can you add option to enlarge or remove image on the right, and to enlarge or make battle scene bigger? in Android?
![Screenshot_2024-05-10-11-10-36-730_org robosturm commander_wars](https://github.com/Robosturm/Commander_Wars/assets/70197430/3f33f53b-3614-4ef7-8140-b6fc226944fd)

**Comment by Robosturm** [comment]
You can change the battle size in the options.
You can change the UI size in the options.
I moved the terrain image to be moved out by the arrow on the right as well instead of being always being visible.

Note: Android is just a side product of the project and want get an extended amount of support.
