### ISSUE TITLE
Trapping on Teleporttiles

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#194]
Unit's can be trapped onto a teleport tile if there are unit's occupying the spaces at the end of a teleporttile path in Fog of War maps. It's currently the only know instance of having unit's occupy a teleporttile.

**Comment by Robosturm** [comment]
Not sure if that's not the correct behaviour.
I can get arguments for both and there's no statement that you can't stop on a teleport tile.

Sidenote: No clue how AW-BW handles that situation.

**Comment by FranticFairy** [comment]
For reference, in AWBW, units that get trap'd while on teleport tiles are stuck there for the entire game because of what teleporttiles are in AWBW.

In my opinion, the ideal solution would be that a unit getting trapped would be sent back to where it came from without revealing anything besides the trapping unit, but idk if that's possible.
