### ISSUE TITLE
Option to pick CO Style before starting game?

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#201]
We can change it in separate menu, but that gives one same style for each player which will use that CO. How about to make an option in setup (before game starts) to pick separate CO Style?

(i.e player one would have Rachel with other suit and custom color, player two, Rachel in main suit and original color)

**Comment by XnKradst** [comment]
I know it's been months since this was posted, but I would second this. I understand this might be a difficult feature to implement, which was probably why it still hasn't been added. However, if you ever add this in the future, I think a way to force a costume or color via code (like a map script) would be cool, as it would allow you to do something like the clones from Dual Strike. A way to check which alt a CO is using would be nice too...

Personally, I think I can use this to make "generic NPC COs" for a custom campaign, kinda like Beast and Davis from DoR. For example, using the same basic CO differentiated only by a forced costume. Combined with the ability to check the CO's current costume, I can *probably* already change profile and music to disguise the fact they're internally the same CO.
