### ISSUE TITLE
Any action in loaded save games results in game ending.

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [Robosturm/Commander_Wars#216]
It is what the title says. Any action conducted in loads results in the immediate game finishing no matter what that action is from the unit menu to unit movement. Another strange thing is that clicking on units with usage automatically goes to the unit menu in said save game.

**Comment by XnKradst** [comment]
The clicking bug has been reported and is already fixed in a hotfix, btw. #209
You can find the hotfix on the same release page over here: https://github.com/Robosturm/Commander_Wars/releases/tag/Beta_12

Not sure if it fixes the game ending bug though. That was reported too, but Robosturm wasn't able to reproduce it.

**Comment by Robosturm** [comment]
Okay could confirm the entering of the victory screen as well.
Oh man restoring script variables from a savegame is broken. 
Ouch
