### ISSUE TITLE
Unit facing be dependent on Team Order rather then Player Order

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#233]
At the moment, the first player units face right, then the second player units face left and so on, to where every odd numbered player's units face right and every even numbered player's units face left.
So my suggestion would be to have this dependent on Teams rather then what Player number you are. This is so that every player on team 1 will have units facing right and every player on team 2 will have units facing left. This would allow a little bit of extra recognition of allied units, at least between an odd teams units and an even teamed unit. This will also assist in a few cases to where two players with similar colors might be a bit more distinguishable.

**Comment by Robosturm** [comment]
I don't see a real benefit in doing so and i always liked the AW-Style of flipping it the way it is.
Since you can always select bad colors so units look the same.
On top the next release will have more distinctable colors also changing some old preset colors of bh/bg/os to the current standard.

What is rather missing is an ingame view showing the team for each player.
