### ISSUE TITLE
Graphs at the end of a game draws too fast

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#29]
**Is your feature request related to a problem? Please describe.**
When a game ends, graphs are displayed. These graphs draws very fast, so fast I don't have time to appreciate it, and I must go back using the buttons at the bottom of the screen to actually see the curves.

**Describe the solution you'd like**
Graphs could be drawing several times slower. If it takes too much time, the player could maybe press the left mouse button to auto-complete the graphs.

**Additional context**
In the option menu, I've set animation speed at 15 (out of 100). Maybe it has something to do with it?

**Comment by Robosturm** [comment]
Changed the update time to an progressiv timing meaning the longer the game went the faster each day is added. Down to a maximum speed. So if the game went 5 days the graph is drawn slower compared to 10 days. 
I also added an option to complete the graph when you click on the graph itself.
I also disabled the auto jump to the next graph it felt pretty weird with the changes.

**Comment by GuardianTempest** [comment]
Well it's working, the graph is slower than instantaneous. However it seems pretty fast, though it could just be because I haven't been hitting enough days yet. Last game played was Dire Range, with me on Team2's position. I'll play more matches and try to draw things out.

I think the line graphs would benefit from some kind of visual effect, where there's a sliding point/spark(?) and the line follows after. It's hard to describe.

**Comment by Robosturm** [comment]
It's not in the current release it's in Beta 6 xD

**Comment by Robosturm** [comment]
Added a progress line to the graphs it's red line from the top to the bottom of the graph which moves every time a new day is added looks quite nice and makes it easier to follow :)
