### ISSUE TITLE
Suggestion: holding the key rather than pressing it to see a unit field of movement/range

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#30]
**Is your feature request related to a problem? Please describe.**
Currently, to see the movement range or firing range of a unit, the player has to press the left or right mouse button once to highlight the applicable tiles, then right-click to make the highlighting disappear.

**Describe the solution you'd like**
To reduce the number of clicks, I would suggest the solution employed by the original Advance Wars games: holding the key or the mouse button. While the key or the mouse button is held, the tiles are highlighted. When the key or the mouse button is released, the tiles are not highlighted anymore.

**Comment by Robosturm** [comment]
This is a discussuable request i prefer it the other way cause i'm not in need to hold down a button the whole time.
So i let the issue open and if more people. Request it i may change it.

**Comment by GuardianTempest** [comment]
I'm also in agreement with Koopanique. I was thinking of bringing this up but I didn't get around to it. With the proposed solution, although you're holding a button down for a little longer at least it's only one total button press instead of two. Plus for twitchier players it's arguably faster, by releasing the button the finger is primed for an immediate button press after, but that's my perspective.

Also, off-topic but I noticed a bug where if you try to close the range indicator by pressing the cancel button while the cursor's on top of the unit, it doesn't work (it does if you move the cursor away from it).

**Comment by Robosturm** [comment]
Okay okay i give up guys. 😄 
@GuardianTempest The bug is now fixed with the reworked while pressed design. -> but i know how this happens. The game removes the input and replaces it with the one it removed. xD
