### ISSUE TITLE
Perk Tooltip Description

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#313]
Currently, when selecting a perk, all you can see is the name. If you hover over a perk, the tooltip that shows up also gives you the name.

In my opinion, perks should either always show their description too so you can see what it does, or show their description in the tooltip and not the perk name.

**Comment by Robosturm** [comment]
Works as intended.
Labels in CoW always show the complete text as tooltip in case of longer translations or to few space.
Hovering the checkbox shows the description.
Basically hover over the object that you can change and you get the tooltip about what's going to happen.
Might not be 100% inuitive but since translations may take more space it's needed.
