### ISSUE TITLE
Yukio and Sensei that spawns units when using power/superpower are shown in the map in Fog of War and Shroud of War, same for power/superpower buffing units and crystal/Alexis healing units

### ISSUE THREAD

**Issue by chopper385** [Robosturm/Commander_Wars#347]
![Commander_Wars_2020-10-28-17-41-00](https://user-images.githubusercontent.com/69113332/97468114-35bdc880-1945-11eb-8d3d-06f5ccac812e.png)

![Commander_Wars_2020-10-28-17-51-47](https://user-images.githubusercontent.com/69113332/97469161-5fc3ba80-1946-11eb-8991-92d8e3e8cf8e.png)

It also does the same when using any power that buffs units with any CO, the powerup animation also plays for all units inside the FoW/SoW. Allows players to see if there is units in the area because of it when it shouldn't.

![Power](https://user-images.githubusercontent.com/69113332/97472633-51779d80-194a-11eb-9132-65ab73a45f38.gif)

And the same when healing with the crystal/alexis skill.
![Healing](https://user-images.githubusercontent.com/69113332/97476491-bdf49b80-194e-11eb-859b-789db6c09314.gif)

Anything that heals and buff are shows in the map in short.
I don't know why I never reported this issue before despite always seeing it.

**Comment by Robosturm** [comment]
As for powers animations it's the same as in the base games.
The difference is that the base games showed an additional overlay making it harder to keep track of it.

As for other healings i'm not sure which idea i'll prefer,
And since as far as i remember crystals never appeared on fog of war maps. It's an open point.
But i get that it gives away some intel.
Though the same is true for things like black canons etc...

I think i only hide the animations for caulder and alexis.
