### ISSUE TITLE
Player Unit Color Bug

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [Robosturm/Commander_Wars#357]
When changing a player's color via a script (setColor), it ends up overriding base colors resulting in a something like this.

Normal Green From Start:

![s2](https://user-images.githubusercontent.com/23581266/100714334-9ea0c200-3383-11eb-8472-0f23f414c639.JPG)

Another Player Color to Green (After the Script):

![s1](https://user-images.githubusercontent.com/23581266/100714330-9cd6fe80-3383-11eb-9268-288e5fd59c56.JPG)

This is the script used.
"map.getPlayer(3).setColor(PLAYER.getDefaultColor(2)"

**Comment by HappyPotatoFunTime** [comment]
Actually, I found more through testing.
The problem is that the base color values are being messed up when certain color values are applied. Most of the base category colors work well however some still are affected.

(Base=Player Assigned Colors aka Red for player 1)

Base Teal Tanks
![s3](https://user-images.githubusercontent.com/23581266/100715537-55517200-3385-11eb-9de5-b6e8cb92e980.JPG)

Custom Red Tanks
![s4](https://user-images.githubusercontent.com/23581266/100715549-5bdfe980-3385-11eb-824e-7842d302dfe3.JPG)

Base Silver Heli
![s5](https://user-images.githubusercontent.com/23581266/100715609-71edaa00-3385-11eb-81a9-d4893298127f.JPG)

Base Crimson Heli
![s6](https://user-images.githubusercontent.com/23581266/100715621-7619c780-3385-11eb-88e7-fed128d5738f.JPG)

Weird how some colors overlap darker value lightness for the pictures.

**Comment by Robosturm** [comment]
You're calling/using the function wrong.
The function has an optional part:
void setColor(QColor Color, qint32 table = -1)
The first is a color the second is a color table that should be used.
If the colortable is invalid the game will create one.

So when you call:
"map.getPlayer(3).setColor(PLAYER.getDefaultColor(2)"
The game will create a new colortable with the given green value, which is completly different to the original AW-Green Colortable.
Since some of the tables used are actually created that way those tables will match since the algorythm is the same.

You can take a look at the function getColorTable in player.js to see which table id is mapped to which color. ;)

**Comment by HappyPotatoFunTime** [comment]
Ah, Thanks
