### ISSUE TITLE
Version 5# Map Editor Unit Glitch and HQ Capture Crash

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [Robosturm/Commander_Wars#36]
With the new update, some things felt a bit broken...
-With maps, when changing between maps through load map in the map editor, the units from the previous map will appear in the changed map. Along that is when you exit map editor and reenter the game crashes.
-When playing a game with multiple of players, if one of the players captures the HQ of another player and previous player has some buildings (not HQ) left, the game crashes. This makes it very hard to play any match with more than 2 players :(

**Comment by Robosturm** [comment]
@HappyPotatoFunTime i was able to verify the map editor glitch and fixed it.
I'm not able to verify the crashing when reentering the map editor. Did you do any specific steps in between the reentering or before leaving the editor?

For the second part i know that the AI crashed the game when capturing an HQ and enemy units where deployed, which is fixed for the next release. Does your crash happens with the AI or as a human player? If as a human player i would need some more information since i'm not able to reproduce it.

Thx for the report and thx in advance for further information.

**Comment by HappyPotatoFunTime** [comment]
So far, only found the crash with AI. I have yet to test it with human players, though thanks for fix!

**Comment by Robosturm** [comment]
Than i fixed that bug.

However i'm curious about the crash when entering the map editor.
How can i reproduce it? So i can fix it.

**Comment by HappyPotatoFunTime** [comment]
The bug occurs when you go into map editor, than load a map with units, followed by loading another map (the units from the previous map will appear in the current map). After this the game goes into a weird state. Exiting to the menu and going back into the map editor will crash the game.

**Comment by Robosturm** [comment]
Okay thx that helped so fixing the unit bug did indead fix the map editor bug.

Thx for your help.
