### ISSUE TITLE
Newly added custom perks don't appear by default for older custom maps

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#368]
Custom perks don't appear by default for custom maps, unless the map was saved with those custom perks enabled.

For example:
1. Save a custom map with no mods enabled. You don't have to actually make a map, just save the blank map you start with.
2. Enable the "Commander Wars Perk Debuffs" mod.
3. Try starting a game on that custom map, and select COs and perks like you normally would.
You'll notice none of the debuff perks are available.

I know this is because of the Perks ban list feature, but I think if a map doesn't have any banned perks, then all perks including custom ones should be allowed in it.

If I remember correctly, this happened with the CO and Unit ban lists before, and there was a similar bug with custom weather, although I think those have already been fixed?

While we're on the subject, I don't really know how to explain this but apparently the game treats custom maps and preinstalled/default ones differently... even though they're all .map files?
By "different", I mean the bug I just described (and other similar issues) only affects custom maps, even though logically the default ones should be affected too (as none of those were saved with custom perk mods enabled), but they aren't affected... because they're *not* custom maps?
That's kinda annoying, and I feel like custom maps should work *exactly* like the default ones.

**Comment by Robosturm** [comment]
Added it to have action and perk bann list to reset to default in case of no edits.
Note: This will only apply to maps saved in the next release. --> See below

As for the different treating:
All maps have a version info about the data stored, when loading them the game checks if the data is available and uses that and in other cases uses the default set.
Since custom maps are stored with the newer version they have the data available. They behave differently compared to the ingame maps which were created with one of the initial releases of CoW.
So the different behaviour is expected and just a result of the date when those maps were created.
And there's no solution to that since that's how the file format is meant to work. So older maps are still compatible with newer versions of CoW.

**Comment by XnKradst** [comment]
> As for the different treating:
> All maps have a version info about the data stored, when loading them the game checks if the data is available and uses that and in other cases uses the default set.
> Since custom maps are stored with the newer version they have the data available. They behave differently compared to the ingame maps which were created with one of the initial releases of CoW.
> So the different behaviour is expected and just a result of the date when those maps were created.
> And there's no solution to that since that's how the file format is meant to work. So older maps are still compatible with newer versions of CoW.

Ah, I see. That makes sense, thanks for clearing things up. I avoided making maps with specific mods enabled because of "bugs" like this, but now that I know this, I can probably just make my custom maps on an older version of CoW.
