### ISSUE TITLE
Suggestion: Allowing to keep stars, but block option to use CO Powers

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#413]
This is the one from the Discord requests.

Giving the option to block the CO Power (For specific CO) but allow him to gather, would allow to make more interesting COs fully focused only on their CO-ZONE

**Comment by Robosturm** [comment]
Won't happen for now and for a long time i rather would expect it to never happen.
Since you can work around it by modding the Actions i don't see a high prio on it either.
The main problem is that this change is completly incompatible with the current ai's and thus a change here won't happen for now.
