### ISSUE TITLE
Make animations and damage calculations simultaneous

### ISSUE THREAD

**Issue by rerpha** [Robosturm/Commander_Wars#443]
**Is your feature request related to a problem? Please describe.**
I would like the battle animations and damage to be simultaneous rather than one unit going after the other. 

**Describe the solution you'd like**
When a unit attacks the animations and damage calculation are performed at the same time for both units just like in the AW games. 

**Describe alternatives you've considered**
- Calculate damage beforehand
- Start the health bar animation at the same time for both
- Start the units being destroyed at the same time for both

**Additional context**
I am happy to work on this as I am now able to build CoW. Feel free to assign me @Robosturm

**Comment by Robosturm** [comment]
So the current version is the solution in the gba games.
1. Since this is clone game i would have your idea as an optional thing (default=off) rather than replacing the current solution
2. The damge is already calculated beforehand the battleanimation only gets the data for displaying the animation
3. Synchronizing the health bars isn't a hard deal. Just checkout the game/battleanimation.cpp
4. However how good the synchronizing for the units works. Maybe tricky may need some further good adjustment in game/battleanimationsprite.cpp.

**Comment by Robosturm** [comment]
Also the js-files should be stay untouched for this or the changes need to be upwars compatible so mods don't need to end up in a mess of refactoring.
If you have questions regarding the current concept on how the Battleanimation works feel free to ask them

**Comment by Robosturm** [comment]
Also in the GameAnimationFactory::createBattleAnimation you may want to make the overworld animation synchron as well though this may look weird
