### ISSUE TITLE
Suggestion: Having the shop icon of units display the unit it unlocks

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#446]
A suggestion to have the icon that displays in the shop be of the unit that the shop item unlocks, rather then just an infantry unit. Since mods could be adding custom units, it could give players more clarity to what the unit is, as other wise they would only be able to identify the shop item by the unit's name alone.

**Comment by Robosturm** [comment]
Since you can click the icon/icon button which pops up the wiki page for the unit co etc.
I don't see a real benefit from having the unit icon shown instead.
I thing having the wiki page grants a lot more info and even if i would see the unit icon if i don't know everything about it already.
I wouldn't gain any information. 
So i don't see a good reason to do so, but maybe you have some other arguments to convince me.

**Comment by Everglass** [comment]
Just to be able to identify the unit at a glance. I don't really have any other arguments other then it having an improved flavour to the shop and have it appear more flashy however :(

Just a quality of life improvement.
