### ISSUE TITLE
Suggestion: Debug mode

### ISSUE THREAD

**Issue by ModDownloading** [Robosturm/Commander_Wars#466]
I think having a debug mode ingame would help with testing various missions. Currently in order to get to a later mission in the AW1 or AW2 campaign, you need to beat all the missions before that point and can't backtrack unless you have a save. I think for testing and experimenting it would be very helpful to have a debug mode that would allow you to:

- Choose any mission in a campaign to play, instead of having to go through them sequentially.
- Bypass immediate start to be able to change AI, change which units can be built, change who the player is playing as, etc.
- Also bypass restrictions on changing pre-battle options.

Having debug mode would let coders catch bugs much more effectively (like #456) and give map makers more ideas to work with by playing with the settings in campaign and war room missions (just like they currently can in the AW: Days of Ruin campaign).

Obviously this also can change scenarios a lot (like being able to play "It's War!" as Olaf, for instance), but balance isn't really a concern here since debug mode would be disabled during multiplayer. I think a simple button to toggle debug mode could fit under the options menu.

**Comment by Robosturm** [comment]
The developer mode will be available via the console. No buttons -> I don't like options like this accesable via the ui.
Some things e.g. rules won't be changeable via the menu. However you can change them using console commands as you can do that right now as well.
The console is the way to go for modders and scripters for maps or campaigns to test things. Since it allows to test things very easy while also providing a huge variety.
