### ISSUE TITLE
war room game with multiple co's unable to capture HQ to win or end game

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#480]
I played Lost Basin in war room and encountered multiple issues, starting with colin's co power didn't give him money, he was paired with Grit.

The more interesting issues were once I had killed all of Sami's units and or captured her HQ she was unable to be defeated, I capped all blue buildings and still wouldn't defeat her... Sonja has the same problem, resulting in me being unable to end the game by victory.

pic 1 is capture of sami's HQ
pic 2 is defeat of all blue units
pic 3 is defeat of all yellow units
pic 4 is all enemies defeated and buildings captured.

![warroom bugs](https://user-images.githubusercontent.com/75344715/120744146-3d32ea80-c4af-11eb-9a30-1d60046a2df0.png)

![wr bug2](https://user-images.githubusercontent.com/75344715/120744236-63f12100-c4af-11eb-8fce-e32ec0b19612.png)

![bug 3](https://user-images.githubusercontent.com/75344715/120744241-66ec1180-c4af-11eb-8769-581f39e69e5f.png)

![bug4](https://user-images.githubusercontent.com/75344715/120744245-69e70200-c4af-11eb-93b6-b3e22716e635.png)

**Comment by TeslaTrooper09** [comment]
mods installed: aw2 image mod, aw airforce mod, awds co mod

**Comment by Robosturm** [comment]
This looks not to be a bug in the code.
But my guess is the map is one of those few maps which have a none default set for rules.
Thus the map has no victory conditions you can easily check that in the rules by going into the info section. 
I'm going to fix the settings for the map ofc.

Regarding Colin i'm going to check if maybe the script gets stuck due to an error.
Also please report one problem per issue. So tracking is a little bit easier. Thx. :)

**Comment by Robosturm** [comment]
Also on another sidenote.
If reporting a bug please make sure. You don't have any custom mods active. --> Cause i'm only testing against vanilla-stuff.

**Comment by TeslaTrooper09** [comment]
copy

**Comment by TheMasterCreed** [comment]
> This looks not to be a bug in the code.
> But my guess is the map is one of those few maps which have a none default set for rules.
> Thus the map has no victory conditions you can easily check that in the rules by going into the info section.
> I'm going to fix the settings for the map ofc.
> 
> Regarding Colin i'm going to check if maybe the script gets stuck due to an error.
> Also please report one problem per issue. So tracking is a little bit easier. Thx. :)

I have a correction to make, it is not due to map rules. I believe this problem needs a closer inspection. I have saved a game right before ending a match and on some occasions the game will not complete and on other occasions the game will complete, and this is on the exact same saved game. I will try and find the log I had.

**Comment by TheMasterCreed** [comment]
[20210721-215702 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/6874225/20210721-215702.Commander.Wars.Crash.log)
[20210725-010653 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/6874226/20210725-010653.Commander.Wars.Crash.log)
[20210725-010657 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/6874227/20210725-010657.Commander.Wars.Crash.log)
I believe all three of these logs reference the issue

**Comment by Robosturm** [comment]
@TheMasterCreed nope this is a completly different problem.
The problem described is that the game never ends. You can just end your turn forvever and never win.
What you report are actually crashes of the game, which have nothing to do with the savegame/savestate itself

**Comment by TheMasterCreed** [comment]
Ah I gotcha
