### ISSUE TITLE
Player funds can go into the negatives

### ISSUE THREAD

**Issue by GuardianTempest** [Robosturm/Commander_Wars#5]
**Describe the bug**
Game doesn't try to stop the player from buying units he can't afford.

**To Reproduce**
What I've done was picked a 2-player map in the Singleplayer screen, although the bug could be done in another other kind of map with any other CO. When deploying units the player selects any one that's too expensive to afford.

**Expected behavior**
The player's funds go into the negative. This can be exploited to purchase expensive units as early as Turn 1.

**Desktop (please complete the following information):**
 - OS: Windows 7
- Game Version: Beta Release 4

**Additional context**
From what little I've played the AI has yet to exploit this bug.

**Comment by Robosturm** [comment]
Weird weird.
Found the bug it only happens if you use keys to build units using the mouse doesn't work. 
The key input bypasses the check if the action is possible. :(
The AI is checking if building a unit. Double checked that so it's not able to exploit it at all.
Going into negative funds however will remain in the game. That's intended. For CO's like Varlot...

**Comment by GuardianTempest** [comment]
Thank you for the quick response! I'll put up more Issues when I see them.
