### ISSUE TITLE
Suggestion: Cooperation Mod Being a Default Mechanic 

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#513]
This is another one of those features that are currently locked away behind a mod that I think should be a default mechanic instead and have some game rules set for it.

First and Foremost, Allies should always have the ability to Refuel allied units and have the choice of healing an allied unit as well with a Black Boat and other support units. (Although it should not automatically default to healing an allied unit in this regard).  
I think these should just be universal mechanics that are always available, as it would improve upon team matches in general. 

The only things I believe should have a checkbox option to disable or enable in the game rules menu are:
- Transporting Allied Units
&
- Allied Buildings Healing Allied Units

As these things could be abused in matches between random players that are paired with each other. 
And they should probably be labeled under a new "Co-op" category since there are other Co-op-related things I want to request for the menu.
EDIT: I guess allied units being able to refuel, repair or support other allied units could also have a checkbox option in the ruleset as well, considering I'm sure there are some people that might not want it.

Note: These are all the features I'm aware of that are added with the mod. So if I didn't mention anything else the mod adds here, it's because I didn't know 'bout it.

**Comment by Robosturm** [comment]
While I understand the request.
The problem with it is that this mod is intentionally not part of the base game cause it may create several problems especially with the interaction of the ai.
Secondly this mod changes the gameplay in such a drastical way that it's not comparable to AW anymore.
And in my opinion enabling the mod is easy enough.
And having it as a mod avoids a lot of programming nightmares for me. ;)

**Comment by Seimix** [comment]
Well, at the very least can allied units have the ability to support other allied units? 
An Allied Black Boat, APC, and other support units should at least always have the ability to choose to refuel, repair, or support a unit on a different but allied army.  A bit infuriating that you can't do this already. (Aside from with the mod, ofc)
Granted, I don't know how this would affect the AI, but I heavily disagree in the regard it would be "too different" from the traditional Advance Wars formula.

**Comment by Robosturm** [comment]
Especially the ability to support other allied units is something, I don't want to see in the vanilla game.
Due to it's very complicated code and the fact that every support ability needs a massive amount of coding to get it to work.
Repairs                   --> Easy
Supply                   -->  Easy but already changes a lot of when it comes to apc's
Buff/Debuff a unit  --> Pure Hell
And since i programmed a lot around with TBS-Games I can say that not having Cooperation in TBS-Games isn't an oversight but is a lot more complicated than you might think from a programming side so games tend to not add it due to it's problems
