### ISSUE TITLE
Can't run Beta release 20

### ISSUE THREAD

**Issue by QuestionMark210** [Robosturm/Commander_Wars#589]
When i try to run latest beta 20 i do always get this:
Commander_Wars.exe - Aplication Error
The application was unable to start correctly (0xc0000005).

**Comment by Robosturm** [comment]
This is a known issue with the pre-release due to missing dll's in the deployment with the msvc-build.
The actual release will be build with mingw which works fine.
Please use an earlier version till either the pre-release can be swapped to mingw (might happen this weekend) or the actual release happens.
Sorry for that but currently i use a beta-version of qt which doesn't fully support mingw, which is why 20 is marked as pre-release.

**Comment by QuestionMark210** [comment]
Ok, but earlier version crash a lot for me with this message:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Commander_Wars.exe
  Application Version:	0.0.0.0
  Application Timestamp:	6097f5f3
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.24384
  Fault Module Timestamp:	5c6e2180
  Exception Code:	c0000005
  Exception Offset:	0003c8c4
  OS Version:	6.1.7601.2.1.0.256.1
Can i fix it somehow?

**Comment by Robosturm** [comment]
Well i fear Commander Wars may not run on Windows 7 at all.
If i interprete the crash message correctly.

**Comment by QuestionMark210** [comment]
(

**Comment by Robosturm** [comment]
If you have an android device you can play CoW on that though in that case you should wait for the update of the pre-release tomorrow.
Sry for that but Windows 7 is an OS no longer supported by Windows
