### ISSUE TITLE
Suggestion: Pause & Deployment Menu Change, and Fog of War Update for Local Multiplayer

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#74]
Aside from the title being a mouthful, there are several things I think should be changed:

I. **Pause Menu Change**
When you're using two COs at once and both of their power meters are filled at the same time, THIS happens: https://i.imgur.com/FGEx6VK.png
Now, this is an issue when using the mouse as; When I'm trying to end my turn, I instinctively move the mouse down to the bottom of the menu to end my turn. However, instead what I end up doing is hitting "Exit Game" by accident. Sure, this is a nitpick, but even if you do take the mouse out of the problem, it still looks a bit wrong for the menu to look like this. 
Now some suggestions I have for this are:
A. Make the Pause Menu "Taller" so it doesn't make another window appear when all CO powers are available.
B. Have a sub-menu in the pause menu for the CO powers OR Game Info, which includes CO & Victory Info. (I guess this issue is partially my fault since I requested the addition of a Surrender Option and more Game-Related info options as well in the Pause menu)

II. **Centering of Deployment Menu**
Now, I know the Deployment menu is already technically centered, but the thing is, the overlay covers up some of the map. So you're mostly going to be looking at the left side of the overlay to play the game. Another issue is that; if you were to mod in enough units, a 3rd Window will appear. Which looks like this:
https://i.imgur.com/fPRvxIQ.png
Now, I don't really know if the Deployment menu would appear below or above the overlay if there were to be more windows, but either way, it wouldn't look too good.
Basically, what I would like for this are:
1. Move the Deployment menu farther away from the overlay (In other words, have it in a fixed position that's away from the overlay, and have it re-position itself there if new windows are added...if possible)
2. If a 3rd Window does appear, have it automatically center better
3. Have the Unit Deployment Menu Max out at three windows, after that, it begins scrolling. (If Possible)
  3A. Alternatively, have it max out at 2 Windows and if any more units are added that exceeds the maximum amount of units that can appear one window, have it start scrolling. 
(I also guess having all menu related options being moved away from the overlay a bit more would be nice too)

III. **Fog of War Change for Local Multiplayer**
Now, this is something already featured in the original games (or at least AW2 & DS). In the original games, when you're playing Local Multiplayer (I.E, using the same computer for two or more teams) in fog of war, and you end your turn, your view of the map is blocked. Keeping you from seeing any army's units or buildings until a button is pressed, then the next army begins their turn. This is to keep you from seeing the enemies unit's after you end your turn. 

Basically, during fog of war:
1. Human Player 1 Ends their turn
2. After doing so, your view of the map is blocked. Keeping you from seeing either armies units and buildings until a button is pressed.
3. After the button is hit, Human Player 2 Starts their turn
4. Repeat

Some things should be noted... Such as the map being blocked in-between turns during fog of war should only happen when the armies are being controlled by HUMAN players. It shouldn't be blocked when fighting an AI. Secondly, it shouldn't happen in-between armies that are on the same team. (For example, the map doesn't get blocked in between Player 1 & Player 2's turn if they're on the same team, although it does get blocked when it switches from one team to another) 
Typically when the map is being blocked, text appears on the screen saying "It's Blue Moon's Turn!" or whatever.

-------
Yes, I know these are mostly nitpicks and they could just be because of my resolution, but I really do think the third thing should be added since it would keep you from accidentally seeing your opponents units during fog of war.

**Comment by XnKradst** [comment]
This reminds me. If you don't mind, I'll mention it here instead of starting a new thread since it's kinda relevant.
I think maybe the CO power commands as shown above should display the COs' names instead of "CO 1" and "CO 2"? Maybe something like "Power (Andy)"? Personally, I prefer that over "Power of Andy" or "Andy's Power".
I just think it can be confusing the way it is now, especially if you have the AW:DS COs mod enabled because the order changes in-game when you swap the COs.

I already did this myself by editing the `getActionText()` function in all 4 CO power action .js files to something like this:
```
this.getActionText = function()
    {
        var i = map.getCurrentPlayer().getCO(0).getCoID();
        var j = Global[i].getName();
        return qsTr("Power (" + j + ")");
    };
```

**Comment by Robosturm** [comment]
As for 1 and 2 i changed the stuff not to your suggestions. I have to put them together since the game makes no difference between any of the ingame input menus. What i did is you can now select the number of items in a row in the option menu. I also changed that the menu prefers to popup not on the right overlay but instead get moved to the left. Since i personnaly prefer having multiple rows instead of one and scrolling won't be an option for the menu for a long long time (I don't see a benefit of adding it right now). So you should avoid point 1 by increasing the items in rows which also decreasses the amount of rows for building units. Added an example screen. 
Note that i simply changed the items per row to 20 put the actual number is up to you and you can see that the menu was shifted to the left instead of going into the overlay.

As for three i'm going to add that one later hopefully before the next release

Changed the naming of the Powers that's a good idea.
@XnKradst you used the qsTr() function wrong. ;) It translates a default string into the the selected language. Since the CO Name is already translated you would do
![Gameplay](https://user-images.githubusercontent.com/48879701/67146618-4137d780-f28d-11e9-8c6d-215a07ca68ab.png)
 it twice. It has no impact at the moment since the game lacks translations for other languages but still...

**Comment by Robosturm** [comment]
Implemented point 3 as well so i'm done here.
