### ISSUE TITLE
Script Variable: Array

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#823]
I have something I want to try, but it requires me saving an array (of units, in this case) as a script variable to be stored and accessed by different things at different times.

Is this currently possible? If not, is there any chance an array script variable - or something else that could achieve the same thing - might be added?

**Comment by Robosturm** [comment]
Currently arrays of strings and ints are supported.
Take a look at ScriptVariable header.
The support of floats can be added if needed.
A support for units won't be added due to the fact that those can't be saved and restored.
Since they would represent pointers which have different memory locations after a savefile gets loaded.

**Comment by Robosturm** [comment]
I assume you have what you need else reooen and mention it
