### ISSUE TITLE
Unable to target water mines with aircraft

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#847]
watermines are all unable to be targeted by a/c even when the weapon tables have damage values for mines

**Comment by Everglass** [comment]
I believe this is due to stealth rules and what they define can attack a stealthed unit. The game doesn't consider seamines to be any different from submarines, so a stealth seamine isn't going to be hit by anything a submarine can't be. So even if they have a damage value for seamines, air won't be able to hit them unless you were to un-stealth them some how. Because I believe for another unit to attack a stealth unit, they have to be a direct unit of the same type (ground, infantry, air, naval).

**Comment by Robosturm** [comment]
As mentioned normal stealth rules apply.
Seamines are currently stealthed not cloaked which may change someday or not.
