### ISSUE TITLE
don't count water mines in unit count

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#867]
if a player has laid any mines and lose all their units but the mines remain they stay in the game until the mines are destroyed as well

**Comment by KBraid** [comment]
it could cause a game to drag on unnecessarily if a player becomes unable to produce more units and has all their units destroyed, but still has mines about that the other player has to now go find to end the match

**Comment by FranticFairy** [comment]
Perhaps a solution could be to, if it's anything but the player's first turn, simply kill off all mines (or even just 'any unit with no ability to attack and capture'?) at the start of a player's turn if no other units are found? This way, mines are automatically removed if a player would've already lost the game due to lack of units, while not breaking potential maps that for some reason start players off with just seamines and factories

**Comment by Robosturm** [comment]
And what is with other cloaked/stealthed units?
It's simple there are units which can clock/stealth themself and don't use fuel and therefore life forever.
If you set the game to win by destroying all other units and nothing else.
And you need to go on a stealth hunt than that's on you.

No units means no units and anything related to this tends to extend the match.

**Comment by Robosturm** [comment]
Changed it to be a toggle option for the rule to ignore watermines default is watermines count
