### ISSUE TITLE
option to start dedicated serever form the comand line.

### ISSUE THREAD

**Issue by Lukas1818** [Robosturm/Commander_Wars#897]
**Is your feature request related to a problem? Please describe.**
If you run Commander Wars server on a headless machine, you can not change settings at the gui as described at the [wiki](https://github.com/Robosturm/Commander_Wars/wiki/Multiplayer).

**Describe the solution you'd like**
A command line option to start the server without open the gui first. As Example `commander-wars --nogui --server PORT LISTENADDRESS PASSWORD` 

**Describe alternatives you've considered**
Creating a script with does try modify the ini file, before starting the game.

**Additional context**
This would it also make possible to create a Docker image, so the game sever can easy be deployed on a server.
Maybe an option to compile Commander Wars without resources, to reduce the binary size, would also be nice.

**Comment by Robosturm** [comment]
@Lone
The wiki page is currently not update.
Dedicated server is currently under a refactoring process and there's a known issue related to hashing the mod/script state.
I've added an option for disabling graphics compilation as well as sound the later was already possible.
Note: If everything works correct with disabled sprites wasn't tested yet.

As for args given.
The actual args will be different and especially the Password part won't be added.
Since the actual game started can have a password and later on a password is more bound to user and it's data if a database will bve supported later on

**Comment by Robosturm** [comment]
Also the configuration for the server is part of the ini. So it's not fully required to use the ui.
Though i admit it's tedious to start the exe, close it, modify the ini and restart it.

**Comment by Lukas1818** [comment]
So I think it would be the best to write a script, witch would create the ini file before starting the server. Thanks

**Comment by lonewolf19991** [comment]
My idea was this and I had discussed this through Discord. A server which is not associated with the client per se, but handles the data through JSON, then this server could send the JSON back and forth between the clients. This would allow the client to be version agnostic, and in turn not have to need to hold any data of the game.

I am writing it through node.js and express, but so far I need to double check how to handle internal IP addresses of devices that are connected to the server from the same External IP.

My idea is to do so through fingerprinting, or somehow getting the internal IP data from the JSON.

Goal with this is to make it so the server itself is lightweight and can be hosted in relatively cheap plans.

Furthermore, the idea is that it has only one IP address and one single port being used regardless of how many active games there are.
