### ISSUE TITLE
Disable map cursor for player when not their turn

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#912]
the map cursor should be disabled for the player when not their turn so that the enemy can use their stealth units or mines without it being able to be tracked by cursor position... they should still be able to interface with the map so they can toggle info and settings.

**Comment by Robosturm** [comment]
The cursor doesn't move if the unit is already stealthed, so you can't track a stralthed unit, but i don't see any benefit nor reason to do this when the unit goes into stealth or out of it, since you can see the animation at the tile.
And not having the cursor move to that point is more annoying than helping anyone.
