### ISSUE TITLE
an aethstetic alternative to silos

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#941]
it seems quite common for mappers to use silos for their terrain stars rather than their functionality, and in my opinion they kinda make a map look rather ugly, so i was thinking of making an alternative terrain type to fill that niche. what do you think?

**Comment by Robosturm** [comment]
I would consider something like a fortress but all things consider i'm not against it.

**Comment by Jocrr** [comment]
I got my mod's fort, if that means anything to you guys

**Comment by KBraid** [comment]
were the depots added in the last update? this is what i made them for

**Comment by Rephath** [comment]
Depots are added. This should close the issue satisfactorily.

**Comment by FranticFairy** [comment]
Here's my two cents: Depots should not fill this role. A depot is "a place for the storage of large quantities of equipment, food, or goods.", not a fortified position. It makes no sense for it to defend as well as a city would.

Here's my suggestion: Make depots a neutral structure (with 1 or 2 stars) that resupplies land units regardless of allegiance, and ask Thae if we can use their bunker sprite as a neutral 3-star defensive option:
https://cdn.discordapp.com/attachments/615556870698041363/1008964671535058994/unknown.png

**Comment by FranticFairy** [comment]
Discussed a little more on Discord, here's a tl;dr of the end result of my idea:

- Take the focus of defense away from Depots, and find another use for them regarding supplies (reduce their defense from _3_ down to 2, or perhaps even 1). There are a few ways this can be done, either as a neutral structure that fully resupplies anyone, a neutral building that does a limited resupply (like either only fuel, or maybe only one of the two at a time, so you need to wait two turns for a full resupply), or something APC-buildable (though this might very well be OP)
- Add a 2-star neutral terrain, perhaps trenches? Thae has made trenches, too. Alternative options include small villages, or something else suitably smaller than a city.
- Add a 3-star neutral terrain, like the bunker Thae made.

https://cdn.discordapp.com/attachments/964830938402025493/1009720741622710272/unknown.png

This way we have more defensive building options, and the opportunity to give Depots a special function.

**Comment by Robosturm** [comment]
Technical DoR did this by moving forest to 3 defense stars and made wastelands a 2 terrain defense tile.
And since CoW tilesets evolve around DoR i changed the forest defense to 3 since it should have been 3 from the beginning.

Since i neither like the bunker nor the depot sprite at the moment none look that aw-like.
I'm against adding trecnes to the game that's something for modding in my opinion.

As for a bunker i can see the usage of a neutral terrain/building with 3 defense like a bunker or fortress but as long as the sprites don't look that good i won't work on that.

Also i don't want to flood the game with to many tiles.
