### ISSUE TITLE
Support for Moddable units that have buff/debuff zones and Actions that can modify units

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#96]
I'm not entirely sure what's all available with what you can do with creating unique unit types, but I was hoping to have the ability to have a unit type that can apply buff to units around them similar to a co zone. As well as one that could apply an attack debuff to enemy units near it.

Also, with the ability to have actions that allow them to modify a unit for a turn, such as to give a single unit, or units around it, more or less damage and defense, increased vision, increased movement points, hidden, remove active turn or give active turn. Also perhaps allow the costs of these abilities to tied to fuel rather then ammo, if you choose so.

**Comment by Robosturm** [comment]
The remove and active turn is already possible same goes for the costs you can do there whatever you want. You could tide it to a hidden value or fuel ammo or nothing as you wish. Since the reduction etc. is dealt in the scripts.

As buffing in a zone i only see the problem that you won't get a nice like for the co-zone other that that those options are not that complicate to be added. Though not before Betaversion 10. ;)

**Comment by Robosturm** [comment]
added option to buff a unit for n-turns. The buff can be applied to offensive, defensive, firerange, movement range and vision range.

**Comment by Robosturm** [comment]
Okay i thought my through debuff and buff zones and i want add them for now.

What you can do alternativly is having a debuff buff zone that is applied at the start of the turn to all units in range or that you can active via an action and than applies to all units in the area.

Having an actual buff/debuff zone is pretty complex and only adds a benefit if a unit would move into the zone. It also reduce the performance mainly for the AI. So from my point of view that's a good enough solution.

Could you go with that @Everglass ?
