### ISSUE TITLE
Map editor optimizations

### ISSUE THREAD

**Issue by AtomicDig219303** [Robosturm/Commander_Wars#981]
Hello Robosturm, here my suggestion.

In a future update would it be possible to optimize the map editor to support bigger map sizes?
I tried to make a really big map (300x150 tiles) and everything worked fine untill i tried to save and reload the .map file.
When I tried to load again the file my game crashed, I tried a few more times but it crashed again.
The ability to make bigger maps will totally improve the creativity of the community allowing us map makers to create longer and better experiences for all Commander Wars players to enjoy.

**Comment by Robosturm** [comment]
So the answer to your request is no.
However there a couple of scenarios:
a) The map file got damaged e.g. cause the game was quit before the map was fully saved. In that case the game simply crashes due to a damaged file. --> Nothing i can do
b) A bug is present in the map loaded and the game crashes in that case it would be helpful to have the map in order to check that
c) You run out of ram this is pretty unlikely unless you run the game on a potato since the game uses maybe 200MB of RAM for a map of that size. --> Here there's nothing i can or will do. I'm not optimizing the game to reduce the footprint of a loaded map. Just to get headaches for handling data and pretty much no benefits outside some very rare large map occassions.

All in all you can attach the map file and i can check if there's a bug in the map loader or the map file is damaged.

**Comment by AtomicDig219303** [comment]
Hi Robosturm, thank you for responding so quickly, you made me realize that my map file was actually damaged.
I'm sorry that I bothered you, I should have checked before posting a comment.
