### ISSUE TITLE
Possible counter-attack damage bug

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#986]
I'm not sure if this is intentional or not (not sure if the canon AW games also do this), but when calculating counter-attack damage, the game seems to take a unit's *exact* HP rather than the rounded HP displayed in-game. What I mean by "exact" is the actual internal HP value of a unit, something like 0.6 or 0.19999977946281433 or whatever.
Normal attacks (non-counter) seem to be unaffected by this.

This means there can be two units of the same type with 5 HP visually, but one of them will do slightly more or less counter-attack damage, since one could have 4.9 HP remaining while the other could have 4.2 HP.

![image](https://user-images.githubusercontent.com/50599768/173414801-f19ec28a-3545-4b1f-91be-fbd93687b8ab.png)
This screenshot demonstrates what I'm talking about: the infantry units here each has 3 *rounded* HP left, but one deals more counter-attack damage than the other because the calculation uses their actual HP (shown by the health bars to the right), when they should be using their visual HP.
Not the best example as the differences are minimal, but with bigger units, this could make counter-attacks a bit unpredictable.

**Comment by Robosturm** [comment]
All damage calculations use the same functions so it either works always correctly or never.
What's mostlikely happening that one inf is always knocked down to 1 hp resulting in the shown damage and the second one is at 2hp at average resulting in the given damage.
Since the original games don't have forecast like this. You can't compare it, but the behaviour is intentional to give you the best and worst results including the actual hp.
